// <auto-generated />
namespace syseng_back.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class shortbody : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shortbody));
        
        string IMigrationMetadata.Id
        {
            get { return "201701271530323_short body"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
